	<div id="menu">		
		<div class="menu-item"><p><a href="<?=$path?>features/">Features</a></p></div>
		<div class="menu-item"><p><a href="<?=$path?>downloads/">Downloads</a></p></div>	
		<div class="menu-item"><p><a href="<?=$path?>tutorials/">Tutorials</a></p></div>
		<div class="menu-item"><p><a href="<?=$path?>reference/">Reference</a></p></div>	
		<div class="menu-item"><p><a href="<?=$path?>development/">Development</a></p></div>		
	</div>
</body>
</html>
