<?php include 'functions.inc'; ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="<?=$path?>shadow.css" rel="stylesheet" type="text/css" />
<link href="<?=$path?>prettify/prettify.css" rel="stylesheet" type="text/css" />
<link rel="shortcut icon" href="<?=$path?>images/favicon.ico" />
	
	<!--[if lt IE 9]>
		<link href="<?=$path?>ie.css" rel="stylesheet" type="text/css" />
	<![endif]-->
	<!--[if gte IE 9]>
		<link href="<?=$path?>nonie.css" rel="stylesheet" type="text/css" />
	<![endif]-->
	<![if !IE]>
		<link href="<?=$path?>nonie.css" rel="stylesheet" type="text/css" />
	<![endif]>	
	
	<script type="text/javascript" src="<?=$path?>prettify/prettify.js?lang=shadow"></script>	